---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r poc-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(maptools)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(ggiraph)
library(leaflet.extras)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
kc_tr_acs <- acs::geo.make(state = "WA",county = "King", tract = "*") 
```

### ACS Data
```{r poc-acs}

# Setup the ACS geographies: Seattle (tracts), YCC (tracts), Seattle (place)
# -----------------------------------------------------------------------------

ycc_geo_acs <- c(
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_sea_sp$TRACTCE)),
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_ycc_sp@data[tr_ycc_sp$NHOOD_ABBR=='CH','GEOID6']),combine = TRUE, combine.term = 'CH'),
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_ycc_sp@data[tr_ycc_sp$NHOOD_ABBR=='CA','GEOID6']),combine = TRUE, combine.term = 'CA'),
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_ycc_sp@data[tr_ycc_sp$NHOOD_ABBR=='FH','GEOID6']),combine = TRUE, combine.term = 'FH'),
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_ycc_sp@data[tr_ycc_sp$NHOOD_ABBR=='CID','GEOID6']),combine = TRUE, combine.term = 'CID'),
        acs::geo.make(state = "WA",county = "King", tract = as.numeric(tr_ycc_sp@data[tr_ycc_sp$NHOOD_ABBR %in% c('CH','CA','FH','CID'),'GEOID6']),combine = TRUE, combine.term = 'YCC'),
        acs::geo.make(state = 'WA', place = "Seattle")
)

# Download the ACS data and save the object as a .rds file
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/poc-orig-acs.rds'))){
        
        tbl <- "B03002"  # census table code
        
        acs.fetch(endyear = 2014, geography = ycc_geo_acs, 
                  table.number = tbl) %>%
                write_rds(root_file('1-data/4-interim/poc-orig-acs.rds'))
        
}

poc_orig_acs <- read_rds(root_file('1-data/4-interim/poc-orig-acs.rds'))


# Process and save the data
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/poc-acs.rds'))){
        poc_acs1 <- poc_orig_acs

poc_acs2 <- poc_acs1[, "B03002_001"] - poc_acs1[, "B03002_003"] 
                        
acs.colnames(poc_acs2) <- "POC"
                        
poc_acs2 %<>%
        cbind(poc_acs1, .)
                        
# Find the proportion of People of Color to the Total population
poc_acs3 <-  
        apply(
                X = poc_acs2[, 22],
                MARGIN = 1,
                FUN = divide.acs,
                denominator = poc_acs2[, 1],
                method = "proportion",
                verbose = FALSE
        ) 
                        
acs.colnames(poc_acs3) <- "POC_PCT"

poc_acs <- poc_acs3

# Save the object

poc_acs %>% saveRDS(root_file('1-data/4-interim/poc-acs.rds'))
}

poc_acs <- read_rds(root_file('1-data/4-interim/poc-acs.rds'))


# Plot the data
# -----------------------------------------------------------------------------

plot(poc_acs)

```

### Seattle Tracts

#### Dataframe
```{r poc-sea-tr-df}

# Convert the `acs` object into a dataframe and save the object
# -----------------------------------------------------------------------------

# Tracts only
if(!file.exists(root_file('1-data/4-interim/poc-sea-tr-df.rds'))){
        
        poc_sea_tr_acs <- poc_acs[poc_acs@geography$tract %in% tr_sea_sp$TRACTCE,]
        
        data.frame(
        geography(poc_sea_tr_acs)["tract"], 
        estimate(poc_sea_tr_acs), 
        1.645 * standard.error(poc_sea_tr_acs)) %>% 
        `colnames<-`(., c("GEOID6", "POC_PCT_EST","POC_PCT_MOE")) %>% 
        mutate(UPPER = POC_PCT_EST + POC_PCT_MOE, 
               LOWER = POC_PCT_EST - POC_PCT_MOE, 
               UPPER = if_else(UPPER > 1, 1, UPPER), 
               LOWER = if_else(LOWER < 0, 0, LOWER)) %>% 
        write_rds(root_file('1-data/4-interim/poc-sea-tr-df.rds'))
}

poc_sea_tr_df <- read_rds(root_file('1-data/4-interim/poc-sea-tr-df.rds'))

# View the df object
# -----------------------------------------------------------------------------

view_poc_dotplot <- function() {
        gg <- ggplot(poc_sea_tr_df, aes(x = reorder(GEOID6, 
                                             POC_PCT_EST), y = POC_PCT_EST))
        gg <- gg + geom_linerange(aes(ymin = LOWER, 
                                      ymax = UPPER), size = 1.5, alpha = 0.25)
        gg <- gg + geom_point_interactive(aes(tooltip = GEOID6), 
                                          size = 3, shape = 21, color = "white", fill = "grey30")
        gg <- gg + scale_x_discrete(expand = c(0.01, 
                                               0))
        gg <- gg + scale_y_continuous(labels = scales::percent)
        gg <- gg + coord_flip()
        gg <- gg + theme_minimal()
        gg <- gg + theme(panel.grid.major.y = element_blank(), 
                         panel.grid.minor.y = element_blank(), 
                         panel.grid.major.x = element_line(linetype = 3, 
                                                           color = "grey30"), 
                         panel.grid.minor.x = element_blank(), 
                         axis.text.y = element_blank())
        gg <- gg + labs(x = NULL, y = NULL, title = "POC", 
                        subtitle = "Description", 
                        caption = "Source: ACS Table B03002, Five-Year Estimates (2010-2014)")
        gg
}

# view_poc_dotplot()

view_poc_dotplot_int <- function() {
        ggiraph(code = {
                print(view_poc_dotplot())
        }, width = 0.66, tooltip_extra_css = "padding:2px;background:rgba(70,70,70,0.1);color:black;border-radius:2px 2px 2px 2px;", 
        hover_css = "fill:#1279BF;stroke:#1279BF;cursor:pointer;")
}

view_poc_dotplot_int()

```

#### Map
```{r poc-sea-tr-sp}

# Join the df to the sp object and save
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/poc-sp.gpkg'))){
        
poc_sp <- tr_sea_sp[,'GEOID6']

poc_sp@data %<>% left_join(poc_sea_tr_df, by = "GEOID6")

poc_sp %>% writeOGR(dsn = root_file('1-data/4-interim/poc-sp.gpkg'),
                    layer = "poc_sp", driver = "GPKG", verbose = FALSE, 
         overwrite_layer = TRUE)
}

poc_sp <-  readOGR(dsn = root_file('1-data/4-interim/poc-sp.gpkg'),
                    layer = "poc_sp", 
                    verbose = FALSE, 
                    stringsAsFactors = FALSE) %>% 
        spTransform(crs_proj)


# View the sp object
# -----------------------------------------------------------------------------

view_poc_sp <- function() {
        abbr <- poc_sp
        
        myYlOrRd <- RColorBrewer::brewer.pal(9, "YlOrRd")[2:7]
        max <- max(abbr@data$POC_PCT_EST) %>% round_any(0.1, 
                                                        ceiling)
        pal <- colorNumeric(palette = myYlOrRd, domain = c(0, 
                                                           max))
        
        myLfltGrey(hideControls = FALSE) %>% 
                addPolygons(data = abbr, smoothFactor = 0, 
                            color = col2hex("white"), weight = 1.5, opacity = 0.5, 
                            fillColor = ~pal(POC_PCT_EST), fillOpacity = 0.75, 
                            popup = ~GEOID6) %>% 
                addLegend(position = "topright", 
                          title = "POC", 
                          pal = pal, 
                          values = c(0, max), 
                          opacity = 0.75, 
                          labFormat = labelFormat(suffix = "%", 
                                                  between = ", ",
                                                  transform = function(x) 100 * x)) %>% 
                addFullscreenControl()
        
}

view_poc_sp()

```

### Yesler Community Collaborative Neighborhoods (tracts and Seattle city)

#### Dataframe

```{r poc-ycc-df}


# Convert the `acs` object into a dataframe and save the object
# -----------------------------------------------------------------------------
if(!file.exists(root_file('1-data/4-interim/poc-ycc-df.rds'))){
        poc_ycc_acs <- poc_acs[poc_acs@geography$tract %!in% tr_sea_sp$TRACTCE,]
        
        data.frame(
        geography(poc_ycc_acs)["NAME"], 
        estimate(poc_ycc_acs), 
        1.645 * standard.error(poc_ycc_acs)) %>% 
        `colnames<-`(., c("NAME", "POC_PCT_EST","POC_PCT_MOE")) %>% 
        mutate(NAME = if_else(NAME == 'Seattle city, Washington',
                              'SEA',
                              NAME),
               UPPER = POC_PCT_EST + POC_PCT_MOE, 
               LOWER = POC_PCT_EST - POC_PCT_MOE, 
               UPPER = if_else(UPPER > 1, 1, UPPER), 
               LOWER = if_else(LOWER < 0, 0, LOWER)) %>% 
        write_rds(root_file('1-data/4-interim/poc-ycc-df.rds'))
}

poc_ycc_df <- read_rds(root_file('1-data/4-interim/poc-ycc-df.rds'))

# View the df object
# -----------------------------------------------------------------------------

view_poc_dotplot <- function() {
        gg <- ggplot(poc_ycc_df, aes(x = reorder(NAME, 
                                             POC_PCT_EST), y = POC_PCT_EST))
        gg <- gg + geom_linerange(aes(ymin = LOWER, 
                                      ymax = UPPER), size = 1.5, alpha = 0.25)
        gg <- gg + geom_point_interactive(aes(tooltip = NAME), 
                                          size = 3, shape = 21, color = "white", fill = "grey30")
        gg <- gg + scale_x_discrete(expand = c(0.01, 
                                               0))
        gg <- gg + scale_y_continuous(labels = scales::percent)
        gg <- gg + coord_flip()
        gg <- gg + theme_minimal()
        gg <- gg + theme(panel.grid.major.y = element_blank(), 
                         panel.grid.minor.y = element_blank(), 
                         panel.grid.major.x = element_line(linetype = 3, 
                                                           color = "grey30"), 
                         panel.grid.minor.x = element_blank(), 
                         axis.text.y = element_blank())
        gg <- gg + labs(x = NULL, y = NULL, title = "POC", 
                        subtitle = "Description", 
                        caption = "Source: ACS Table B03002, Five-Year Estimates (2010-2014)")
        gg
}

# view_poc_dotplot()

view_poc_dotplot_int <- function() {
        ggiraph(code = {
                print(view_poc_dotplot())
        }, width = 0.66, tooltip_extra_css = "padding:2px;background:rgba(70,70,70,0.1);color:black;border-radius:2px 2px 2px 2px;", 
        hover_css = "fill:#1279BF;stroke:#1279BF;cursor:pointer;")
}

view_poc_dotplot_int()


```

#### Map

```{r poc-ycc-sp}

# Join the df to the sp object and save
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/poc-ycc-sp.gpkg'))){
        
poc_ycc_sp <- nhood_ycc_sp[,'NHOOD_ABBR']

poc_ycc_sp@data %<>% left_join(poc_ycc_df, by = c("NHOOD_ABBR" = "NAME"))

poc_ycc_sp %>% writeOGR(dsn = root_file('1-data/4-interim/poc-ycc-sp.gpkg'),
                    layer = "poc_ycc_sp", driver = "GPKG", verbose = FALSE, 
         overwrite_layer = TRUE)
}

poc_ycc_sp <-  readOGR(dsn = root_file('1-data/4-interim/poc-ycc-sp.gpkg'),
                    layer = "poc_ycc_sp", 
                    verbose = FALSE, 
                    stringsAsFactors = FALSE) %>% 
        spTransform(crs_proj)


# View the sp object
# -----------------------------------------------------------------------------

view_poc_ycc_sp <- function() {
        abbr <- poc_ycc_sp
        
        myYlOrRd <- RColorBrewer::brewer.pal(9, "YlOrRd")[2:7]
        max <- max(abbr@data$POC_PCT_EST) %>% round_any(0.1, 
                                                        ceiling)
        pal <- colorNumeric(palette = myYlOrRd, domain = c(0, 
                                                           max))
        
        myLfltGrey(hideControls = FALSE) %>% 
                addPolygons(data = abbr, smoothFactor = 0, 
                            color = col2hex("white"), weight = 1.5, opacity = 0.5, 
                            fillColor = ~pal(POC_PCT_EST), fillOpacity = 0.75, 
                            popup = ~NHOOD_ABBR) %>% 
                addLegend(position = "topright", 
                          title = "POC", 
                          pal = pal, 
                          values = c(0, max), 
                          opacity = 0.75, 
                          labFormat = labelFormat(suffix = "%", 
                                                  between = ", ",
                                                  transform = function(x) 100 * x)) %>% 
                addFullscreenControl()
        
}

view_poc_ycc_sp()


```




