---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r tracts-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(sf)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)

```

```{r tracts-colors}
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
```


### YCC Census Tracts
The YCC neighborhoods represented as US Census tracts.

```{r tracts-ycc-nhoods}

if(!file.exists(root_file('1-data/4-interim/tr-ycc-sp.gpkg'))){
        
        geoids <- c("007900", "008600", "007401", "007500", "008300", "008400", 
                    "008500", "008700", "008800", "009000", "009100", "007600", 
                    "007402", "009200")
        
        cid <- c('009200','009100')
        fh <- c('008500','008600')
        ca <- c('009000','008700','008800','007900')
        ch <- c('008300','008400','007500','007402','007401','007600')
        
        tr_ycc_sf <- 
                st_read(dsn = root_file('1-data/4-interim/tr-sea-sp.gpkg')) %>% 
                filter(GEOID6 %in% geoids) %>% 
                mutate(
                        NAME_FULL = case_when(.$GEOID6 %in% cid ~ "Chinatown International District",
                                              .$GEOID6 %in% fh ~ "First Hill",
                                              .$GEOID6 %in% ca ~ "Central Area",
                                              .$GEOID6 %in% ch ~ "Capitol Hill"),
                        NAME = case_when(.$GEOID6 %in% cid ~ "CID",
                                               .$GEOID6 %in% fh ~ "FH",
                                               .$GEOID6 %in% ca ~ "CA",
                                               .$GEOID6 %in% ch ~ "CH"),
                        GEOID = as.character(GEOID),
                            GEOID6 = as.character(GEOID6)
                ) %>% 
                select(NAME,NAME_FULL,GEOID,GEOID6,geom)
        
        tr_ycc_sf %>% 
                st_write(dsn = root_file('1-data/4-interim/tr-ycc-sf.gpkg'),
                         layer = 'tr_ycc_sf',
                         driver = 'GPKG',
                         quiet = TRUE,
                         factorsAsCharacter = TRUE)
}

tr_ycc_sf <- 
        st_read(dsn = root_file('1-data/4-interim/tr-ycc-sf.gpkg'), quiet = TRUE) %>% 
        mutate_if(is.factor,as.character) %>% 
        mutate(NAME_FCT = factor(NAME_FULL,
                                 levels = c('Capitol Hill',
                                            'Central Area',
                                            'First Hill',
                                            'Chinatown International District'),
                                 ordered = TRUE)) %>% 
        select(everything(),geom)

pal <- colorFactor(pal_rgb_4,tr_ycc_sf$NAME_FCT)

tr_ycc_sf %>% 
        as('Spatial') %>% 
        myLfltGrey() %>% 
        addPolygons(
                    fillColor = ~pal(NAME_FCT), 
                    fillOpacity = .85,
                    color = col2hex('white'),
                    opacity = 1,
                    weight = .5,
                    smoothFactor = 0) %>% 
        addLegend(title = NULL,position = 'topright',pal = pal, values = ~NAME_FCT,opacity = .85)



```

### YCC Neighborhoods
The YCC neighborhoods represented as merged US Census tracts.

```{r tracts-ycc-nhoods-merged}

# Dissolve YCC tracts by Neighborhood and save as sp object
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/ycc-nhood-tr-sf.gpkg'))){
        
        ycc_nhood_tr_sf <-
                tr_ycc_sf %>%
                group_by(NAME) %>%
                summarise_all(first) %>%
                rbind(tr_ycc_sf) %>%
                as('Spatial') %>%
                st_as_sf()
        
        ycc_nhood_tr_sf %>% st_write(dsn = root_file('1-data/4-interim/ycc-nhood-tr-sf.gpkg'),
                                     layer = 'ycc_nhood_tr_sf',
                                     driver = 'GPKG',
                                     quiet = TRUE)
        
        
}

ycc_nhood_tr_sf <-  
        st_read(dsn = root_file('1-data/4-interim/ycc-nhood-tr-sf.gpkg'),quiet = TRUE) %>% 
        mutate_if(is.factor,as.character) %>% 
        mutate(NAME_FCT = factor(NAME_FULL,
                                 levels = c('Capitol Hill',
                                            'Central Area',
                                            'First Hill',
                                            'Chinatown International District'),
                                 ordered = TRUE))

# Map
ycc_nhood_tr_sf %>% 
                slice(1:4) %>% 
                as('Spatial') %>% 
                myLfltGrey() %>% 
                addPolygons(
                    fillColor = ~pal(NAME_FCT), 
                    fillOpacity = .85,
                    color = col2hex('white'),
                    opacity = 1,
                    weight = .5,
                    smoothFactor = 0) %>% 
        addLegend(title = NULL,position = 'topright',pal = pal, values = ~NAME_FCT,opacity = .85)

```



