---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r tracts-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
```



### Introduction
Insert text here.

```{r tracts-intro}

if(!file.exists(root_file('1-data/4-interim/tr-ycc-sp.gpkg'))){
        
        geoids <- c("007900", "008600", "007401", "007500", "008300", "008400", 
                    "008500", "008700", "008800", "009000", "009100", "007600", 
                    "007402", "009200")
        
        cid <- c('009200','009100')
        fh <- c('008500','008600')
        ca <- c('009000','008700','008800','007900')
        ch <- c('008300','008400','007500','007402','007401','007600')
        
        tr_ycc_sp <- 
                subset(tr_sea_sp, GEOID6 %in% geoids)
        
        tr_ycc_sp@data %<>% mutate(NHOOD = case_when(.$GEOID6 %in% cid ~ "Chinatown International District",
                                                  .$GEOID6 %in% fh ~ "First Hill",
                                                  .$GEOID6 %in% ca ~ "Central Area",
                                                  .$GEOID6 %in% ch ~ "Capitol Hill"),
                                   NHOOD_ABBR = case_when(.$GEOID6 %in% cid ~ "CID",
                                                  .$GEOID6 %in% fh ~ "FH",
                                                  .$GEOID6 %in% ca ~ "CA",
                                                  .$GEOID6 %in% ch ~ "CH")) %>% 
                select(GEOID,GEOID6:NHOOD_ABBR)
        
        tr_ycc_sp %>% writeOGR(dsn = root_file('1-data/4-interim/tr-ycc-sp.gpkg'),
                            layer = 'tr_ycc_sp',
                            driver = 'GPKG',
                            verbose = FALSE)
}

tr_ycc_sp <- readOGR(dsn = root_file('1-data/4-interim/tr-ycc-sp.gpkg'),
                     layer = 'tr_ycc_sp',
                     verbose = FALSE,stringsAsFactors = FALSE)
tr_ycc_sp@data %<>% mutate(NHOOD_FCT = factor(NHOOD,levels = c('Capitol Hill',
                                                               'Central Area',
                                                               'First Hill',
                                                               'Chinatown International District'),
                                              ordered = TRUE))
pal <- colorFactor(pal_rgb_4,tr_ycc_sp$NHOOD_FCT)

myLfltGrey() %>% 
        addPolygons(data = tr_ycc_sp, 
                    fillColor = ~pal(NHOOD_FCT), 
                    fillOpacity = .85,
                    color = col2hex('white'),
                    opacity = 1,
                    weight = .5,
                    smoothFactor = 0) %>% 
        addLegend(position = 'topright',pal = pal, values = tr_ycc_sp$NHOOD_FCT,opacity = .85)



```







