---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r tr-vars-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(maptools)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(ggiraph)
library(leaflet.extras)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)

```


```{r make-tr-vars}

# Collect all the files that have tract-aggregated variables

if(!file.exists(root_file('1-data/5-tidy/tr-vars-df.rds'))){
        file_list <-
        list.files(root_file('1-data/4-interim/'))[grep('all-df',list.files(root_file('1-data/4-interim/')))] %>% 
        paste0(root_file('1-data/4-interim/'),.)

tr_vars <- 
        bind_rows(purrr::map(file_list, read_rds)) %>% 
        gather(VAR_NAME,ESTIMATE,matches('PCT_EST'),na.rm = TRUE) %>% 
        mutate(VAR_NAME = str_replace(VAR_NAME,'_PCT_EST','')) %>% 
        gather(VAR_NAME_MOE,MOE,matches('PCT_MOE'),na.rm = TRUE) %>% 
        select(VAR_NAME,NAME,ESTIMATE,MOE,UPPER,LOWER)

# Save the object
tr_vars %>% write_rds(root_file('1-data/5-tidy/tr-vars-df.rds'))
}

tr_vars_df <-  read_rds(root_file('1-data/5-tidy/tr-vars-df.rds'))


```





